# Generated by Django 2.1.5 on 2019-02-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='work',
        ),
    ]
